refactor(git-hooks): replace pre-commit script with a new implementation and comment out pre-push checks

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -17,12 +17,12 @@ do
   if [ "$branch_name" = "$protected_branch" ]; then
     bockPush $protected_branch
   else
-    if ! checkDocker || ! checkDockerCompose; then
-      echo "❌ Pre-push checks failed. Please fix the issues before pushing your changes."
-      exit 1
-    fi
-    cleanImages
-    echo "✅ Pre-push checks completed for branch '$branch_name'."
+    # if ! checkDocker || ! checkDockerCompose; then
+    #   echo "❌ Pre-push checks failed. Please fix the issues before pushing your changes."
+    #   exit 1
+    # fi
+    # cleanImages
+    # echo "✅ Pre-push checks completed for branch '$branch_name'."
   fi
 done
 
