feat(git-hooks): streamline pre-push hook for Docker build checks

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -2,14 +2,50 @@
 
 protected_branch="main"
 
+bockPush() {
+  echo "❌ Direct push to '$1' branch is not allowed."
+  echo "🔒 This branch is protected. Please open a pull request instead."
+  exit 1
+}
+
+checkDockerBuild() {
+  if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]; then
+    echo "❌ Missing arguments for Docker build check."
+    exit 1
+  elif [ ! -d "$3" ]; then
+    echo "❌ Directory '$3' does not exist."
+    exit 1
+  elif [ ! -f "$2" ]; then
+    echo "❌ Dockerfile '$2' not found in $3."
+    exit 1
+  fi
+
+  echo "🔍 Checking Docker build for '$1' in $3..."
+
+  docker build -t $1 -f $2 $3 > /dev/null 2>&1 
+  if [ $? -ne 0 ]; then
+    echo "❌ Docker build $1 failed."
+  else
+    echo "✅ Docker build $1 succeeded."
+    docker rmi $1 > /dev/null 2>&1
+  fi
+}
+
+checkDocker() {
+  checkDockerBuild "test-backend" "Dockerfile" "./backend"
+  checkDockerBuild "test-frontend" "Dockerfile" "./frontend"
+  checkDockerBuild "test-nginx" "Dockerfile" "./nginx"
+}
+
 while read local_ref local_sha remote_ref remote_sha
 do
   branch_name=$(echo "$remote_ref" | sed 's|refs/heads/||')
 
   if [ "$branch_name" = "$protected_branch" ]; then
-    echo "❌ Direct push to '$protected_branch' branch is not allowed."
-    echo "🔒 This branch is protected. Please open a pull request instead."
-    exit 1
+    bockPush $protected_branch
+  else
+    checkDocker
+    echo "✅ Pushing to '$branch_name' branch is allowed."
   fi
 done
 
